DEFAULT linux
LABEL linux
  KERNEL /Image
  FDT /sg2002-licheerv-nano-we.dtb
  APPEND earlycon=sbi console=ttyS0,115200 console=ttyGS0,115200 root=/dev/mmcblk0p2 rw rootwait clk_ignore_unused log_buf_len=256K
